### ISSUE TITLE
A few questions!

### ISSUE THREAD

**Issue by DarylDixonLS** [MrNeta/GT-MP-SimpleRoleplay#2]
1: Eating and drinking does not go down! (ProgressBar does not change)
2: Custom Character Creator does not work. You can not change your character.

 
Can this be installed? And if so how? (Am beginners - sorry)
1: MoneyAPI
https://gt-mp.net/forum/thread/457-moneyapi/
2: House Script (Furnitures, Money & Weapon Storage)
https://gt-mp.net/forum/thread/1156-house-script-furnitures-money-weapon-storage/
3: Courier Script
https://gt-mp.net/forum/thread/3377-courier-script/

PS: Follow "LS CUSTOM SERVICE"?

**Comment by MrNeta** [comment]
1. You must create a timer to reduce food and water after a specified time. (This is currently not implemented)
2. As in the description describes "Simplified / early version" (Only First/Last Name and Gender)
---------------------------
Why do you want implement the money api?
It exist a [money system](https://github.com/MrNeta/GT-MP-SimpleRoleplay/blob/master/Server/Services/MoneyService/MoneyService.cs).

You must find your own way to implement it.
I already said I will not offer Active Help or Support for this script.

Greets Neta
