### ISSUE TITLE
Error on start of gtmp simple roleplay

### ISSUE THREAD

**Issue by MisterElFantastico** [MrNeta/GT-MP-SimpleRoleplay#3]
Hey,

i've download a fresh copy of your repo and compile the gtmp server (getting no errors or warnings)
On server start there is only a black console with no stdout; Getting the following error on screenshot (attached) while closing the console.

![unbenannt](https://user-images.githubusercontent.com/17139000/37329434-18ef0e0e-269e-11e8-961d-30950afdd7de.PNG)

**Comment by MrNeta** [comment]
I can't do anything, with such less information.
Check the server without start the gamemode, because the gamemode should start after the server is ready.
